USE nota_fiscal_normalizada;

CREATE OR REPLACE VIEW DaysOfWeek AS
SELECT 'SEGUNDA-FEIRA'
UNION
SELECT 'TERÇA-FEIRA'
UNION
SELECT 'QUARTA-FEIRA'
UNION
SELECT 'QUINTA-FEIRA'
UNION
SELECT 'SEXTA-FEIRA'
UNION
SELECT 'SABADO'
UNION
SELECT 'DOMINGO';

SELECT * FROM DaysOfWeek